\documentclass{article}
\usepackage{amsmath} %This allows me to use the align functionality.
                     %If you find yourself trying to replicate
                     %something you found online, ensure you're
                     %loading the necessary packages!
\usepackage{amsfonts}%Math font
\usepackage{graphicx}%For including graphics
\usepackage{hyperref}%For Hyperlinks
\usepackage{natbib}        %For the bibliography
\bibliographystyle{apalike}%For the bibliography
\usepackage[margin=1.0in]{geometry}
\usepackage{float}
\begin{document}
\SweaveOpts{concordance=TRUE}
\SweaveOpts{width=8,height=5}%set the size of the graphs to fit nicely on a 8.5x11 sheet
\noindent \textbf{MA 354: Data Analysis I -- Fall 2019}\\%\\ gives you a new line
\noindent \textbf{Homework 0:}\vspace{1em}\\
\emph{Complete the following opportunities to use what we've talked about in class. 
These questions will be graded for correctness, communication and succinctness. Ensure
you show your work and explain your logic in a legible and refined submission. If you
make a mistake while completing this assignment do not delete it -- instead, make a note
about why it's a mistake, how you realized it, and how you fixed it. The best, most 
productive recovery from a mistake will receive a 5 point bonus.}
%Comments -- anything after % is not put into the PDF
\begin{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%  Question 0
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item[0.] \textbf{Complete weekly diagnostics.} Upon completion of this assignment
  reflect, in a few sentences, on what you've learned since the beginning of the semester.
  Think about an mention any concepts you want or need to continue working on and
  list at least one goal for the next assignment.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%  Question 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item \textbf{Writing Functions and Loops.} Create a function called \texttt{f1} 
  in \texttt{R}, in as few lines as possible that represents the  following function.
    \[f_1(x) = \ln\left(\sqrt{x*10^3}\right)\]
    Compare the runtime of your function to the one below using a loop that saves 
    the runtime of each function over 1000 iterations. Summarize and compare the results.
<<>>=
f2 <- function(x){
  a<- x*10^3
  b<- sqrt(a)
  c<- log(b)
  return(c)
}
f2(1)
@
You can track the runtime of code using the following \texttt{R} code.
<<>>=
start_time <- Sys.time()
#do things you want to time here
end_time <- Sys.time()
runtime <-end_time - start_time
@
You might want to report this runtime in your .pdf document, but you'll find that the 
runtime changes each time you compile your document. You can pass variable values in \texttt{R}
to the document using the \texttt{Sexpr} command. For example, the runtime of the comment above
is \Sexpr{round(runtime,3)} seconds.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%  Question 2
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item \textbf{Conditional Statements and Loops.} Assess which is faster.
  \begin{enumerate}
    \item Generate 1000 random integers between 1 and 1000 with replacement with
    the following \texttt{R} code.
<<>>=
random.ints<-sample(x=1:1000,size=1000,replace=TRUE)
@    
    Then, using a loop, create a vector named \texttt{random.type} that is ``odd"
    when the corresponding value in \texttt{random.ints} is odd and ``even" otherwise.
    \begin{enumerate}
      \item Add elements to the vector called \texttt{random.type} as they
      are decided; e.g., for an iteration where the value is odd we add
      an element using \texttt{random.type<-c(random.type,"odd")}.
      \item Create an empty vector of size 1000 (with \texttt{NA} entries) to 
      start and place elements into the vector; e.g., for iteration $i$
      where the value is odd we place the element using \texttt{random.type[i]}.
    \end{enumerate}
    Which is faster?
\end{enumerate}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%  Question 3
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item \textbf{Conditional Statements and Loops} Each new term in the Fibonacci sequence is 
  generated by adding the previous two terms. By starting with 1 and 2, the first 
  10 terms will be 1, 2, 3, 5, 8, 13, 21, 34, 55, 89. Find the sum of the even terms in the 
  Fibonacci sequence whose values do not exceed one million.
  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%  Question 4
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%  
  \item  \textbf{Conditional Statements and Loops} A palindromic number reads the same 
  both ways. The largest palindrome made from the product of two 2-digit numbers is 
  $9009 = 91 \times 99$. Find the largest palindrome made from the product of two 3-digit numbers.
  
  You can get the reverse of a number using the ``stringr" package for \texttt{R}
  (practice Sweave by putting by the citation here) as follows.
<<>>=
install.packages("stringr",repos = "https://cloud.r-project.org")
library(stringr)
number.to.reverse <- 1234
#creates a list containing a vector of characters
(split.number<-str_split(number.to.reverse,pattern=""))
(split.number<-split.number[[1]]) #takes just the vector
(split.number.reversed <- rev(split.number)) #reverses the order of the vector
(reversed.number <- paste(split.number.reversed, collapse="")) #paste items back together
(reversed.number<-as.numeric(reversed.number)) #treat it like a number
@
\textbf{Remark:} You'll find that the solution to this question will elongate the
compiling time for the .pdf. That's okay. Once you're happy with the solution 
you can type the output into your code chunk and set eval=FALSE between the left
and right arrows.
\newpage
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%  Question 5
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  \item \textbf{(Working with Data)} Below you will load and summarize a dataset 
  containing 575 observations of drug treatments. The data includes the following
  \begin{itemize}
    \item ID --	Identification Code	(1 - 575)
    \item AGE	-- Age at Enrollment	(Years)
    \item BECK -- Beck Depression Score	(0.000 - 54.000)
    \item HC --	Heroin/Cocaine Use During	3 Months Prior to Admission (1 = Heroin
    \& Cocaine; 2 = Heroin Only, 3 = Cocaine Only; 4 = Neither Heroin nor Cocaine)
    \item IV -- History of IV Drug Use	(1 = Never; 2 = Previous; 3 = Recent)
    \item IV3	-- Recent IV use	(1 = Yes; 0 = No)
    \item NDT -- Number of Prior Drug Treatments (0 - 40)
    \item RACE -- Subject's Race	(0 = White; 1 = Non-White)
    \item TREAT -- Treatment Randomization (0 = Short Assignment;	1 = Long Assignment)
    \item SITE -- Treatment Site (0 = A; 1 = B)
    \item LEN.T	-- Length of Stay in Treatment (Days Admission Date to Exit Date)	
    \item TIME -- Time to Drug Relapse (Days Measured from Admission Date)
    \item CENSOR -- Event for Treating Lost to Follow-Up as Returned to Drugs 
    (1 = Returned to Drugs or Lost to Follow-Up; 0 = Otherwise)
    \item etc.
  \end{itemize}
  \begin{enumerate} %this begins a lettered enumerate so I can ask more 
                    %than one question in a question.
    \item Load the data provided in the ``quantreg" package for \texttt{R} \citep{quantreg}.
<<eval=FALSE>>=
install.packages("quantreg",repos = "http://cloud.r-project.org/")
library("quantreg")
data("uis")
@

    \item Numerically summarize the Beck Depression Score of the observed drug 
    treatment patients. Note the following designations of the test when interpreting
    your results.
    \begin{itemize}
      \item 0-13: minimal depression
      \item 14-19: mild depression
      \item 20-28: moderate depression
      \item 29-63: severe depression.
    \end{itemize}
    \item Graphically summarize the Beck Depression Score of the
    observed drug treatment patients. Interpret the results through 
    the lens of the scale above.
    \item List three questions about drug use that we might be able to answer based on the 
    data we have.
  \end{enumerate}
\newpage
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  %%%%%%%%%  Question 6
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    \item \textbf{(Working with Data)} Hepatitis C is a disease 
    that affects the liver. The virus that causes hepatitis C 
    is spread through blood or bodily fluids of an infected person. 
    The virus is often difficult to diagnose because there are few unique 
    symptoms. Those infected, however, sometimes experience jaundice -- a 
    condition that causes yellowing of the skin or eyes, as the liver 
    is infected.

    \cite{Bracht16} consider the human microfibrillar-associated protein 4,
    or MFAP4, and its role in disease-related tissue. Stage 0--no fibrosis; 
    Stage 1--enlarged, fibrotic portal tracts; Stage 2--periportal fibrosis 
    or portal-portal septa, but intact architecture; Stage 3--fibrosis with
    architectural distortion, but no obvious cirrhosis; and Stage 4--probable
    or definite cirrhosis.

    Previously, it has been shown that MFAP4 is a biomarker candidate for hepatic
    fibrosis and cirrhosis in hepatitis C patients. The analysis of \cite{Bracht16}
    aimed to consider the ability of MFAP4 to differentiate between stages of the 
    disease -- fibrosis stages (0-2) and cirrhosis (3-4) based on the Scheuer 
    scoring system.
    
    Below, I load the data and calculate the age of patients using the ``lubridate"
    package for \texttt{R} \citep{lubridate}.
<<>>=
fn<-"http://cipolli.com/students/data/biomarker.csv"
dat <- read.csv(file=fn, header=TRUE, sep=",")
head(dat)
###Calculate the age of each subject
install.packages("lubridate",repos = "http://cloud.r-project.org/")
library(lubridate)
###Create Date Variable for Date Sampled
dos<-mdy(dat$Date.of.sampling)
dos.year<-year(dos)
###Create age Variable
age <- dos.year - dat$Year.of.Birth
###Add age to original dataset
dat<-data.frame(dat,age)
@
  \begin{enumerate}
  \item Recreate Table 1 in \href{the paper}{https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4932744/}. 
  Add a row to this table labeled ``Median age IQR." I've provided the LaTeX code for the
  table and made the first entry so you can see how it works.

\begin{table}[H]
  \centering
    \begin{tabular}{lccccccc}\hline
    Fibrosis Stage    & F0 & F1 & F2 & F3 & F4 & All\\\hline\hline
    \textbf{Age}                &&&&&&\\
    Mean age SD        &  $43.75 \pm 12.11$      &        &
                                &        &
                                &        \\
    Median age IQR     &        &        &
                                &        &
                                &        \\
    \textbf{Gender}             &&&&&&\\
    Women              &        &        &
                                &        &
                                &        \\
    Men                &        &        &
                                &        &
                                &        \\
    Number of patients &        &        & 
                                &        &
                                &        \\
    \textbf{HCV genotype}       &&&&&&\\
    1                  &        &        & 
                                &        &
                                &        \\
    2                  &        &        & 
                                &        &
                                &        \\
    3                  &        &        & 
                                &        &
                                &        \\
    4                  &        &        & 
                                &        &
                                &        \\
    Other              &        &        & 
                                &        &
                                &        \\
    NA                 &        &        & 
                                &        &
                                &        \\\hline
    \end{tabular}
    \caption{Patient cohorts characteristics, subdivided by fibrosis stage}
  \end{table}
  \item Create several graphs that may be helpful for the researchers.
  \end{enumerate}
\end{enumerate}
\newpage
\bibliography{bib}
\end{document}
